project:
  type: website

title: "Suleman S, Madsen AL, Ängquist LH, et al. Supplementary material for (Genetic underpinnings of fasting and oral glucose-stimulated based insulin sensitivity indices)"
format:
  html:
    layout:
      - single-column


execute:
  freeze: auto
